- src/pages/Loading.jsx
- src/pages/Owner/OwnerPracticeRoom.jsx
- src/pages/User/UserPayment.jsx
- src/pages/User/UserPracticeRoom.jsx
> test: 모바일, PC 확인 테스트 코드 추가

- src/Components/MainHeader.jsx
- src/pages/User/User.jsx
>  #1 [FEAT] 마이페이지 작성 
- margin을 최대한 정리하여 padding으로 변경
- 모바일로 접속한 경우 디자인이 뭉개지는 문제 수정
- TopContent, BottomContent가 높이를 먼저 가지고 나머지 높이를 CenterContent가 가지도록 추가
- MainHeader의 Container의 디자인 주석처리 비활성화
- PC
- 모바일
> feature: 마이페이지 모바일에서 뭉개지는 문제 수정

- src/Components/PracticeRoomDetailCard.jsx
- src/assets/userDetailRoom.js
- src/pages/User/UserPracticeRoom.jsx
> feature: 이용자 연습실 페이지 디자인 수정

- src/pages/Main.jsx
> fix: Dropdown 소문자를 DropDown으로 변경

- package-lock.json
- src/Components/Calendar.css
- src/Components/Calendar.jsx
- src/Components/Chart.jsx
- src/Components/OwnerReservationStat.jsx
- src/pages/Owner/OwnerRevenue.jsx
> Fix calendar design

- src/App.jsx
- src/Components/AddPracticeRoom.jsx
- src/Components/OwnerPracticeRoomDetailCard.jsx
- src/pages/Owner/AddPracticeRoom.jsx
- src/pages/Owner/OwnerPracticeRoom.jsx
> feature: 대여자 페이지 - 연습실 내부 방 목록 페이지 & 변경 페이지 구현

- src/Components/Calendar.css
- src/Components/Calendar.jsx
- src/Components/DateSelector.jsx
- src/Components/PracticeRoomCard.jsx
- src/Components/PracticeRoomDetailCard.jsx
- src/pages/Main.jsx
- src/pages/Owner/Owner.jsx
- src/pages/Owner/OwnerRevenue.jsx
- src/pages/User/UserReservation.jsx
> feature: 날짜 컴포넌트 추가

- src/Components/JoinHeader.jsx
- src/Components/MainHeader.jsx
- src/Components/ProgressBar.jsx
- src/Components/RootContainer.jsx
- src/pages/Join/JoinCategory.jsx
- src/pages/Join/JoinInfo.jsx
- src/pages/User/User.jsx
> feature: 프로그레스 바 컴포넌트 구현

- src/App.jsx
- src/Components/AddPracticeRoom.jsx
- src/Components/Calendar.jsx
- src/Components/Chart.jsx
- src/Components/ReservationCard.jsx
- src/pages/Join/JoinInfo.jsx
- src/pages/Loading.jsx
- src/pages/Owner/AddPracticeRoom.jsx
- src/pages/Owner/Owner.jsx
- src/pages/Owner/OwnerPracticeRoom.jsx
- src/pages/Owner/OwnerRevenue.jsx
- src/pages/User/UserPayment.jsx
- src/pages/User/UserReservation.jsx
> featur: 대여자 수익 및 예약 결제 api 연결, 일부 디자인 수정

- src/assets/category.js
- src/assets/owner.js
- src/pages/Loading.jsx
- src/pages/MainPracticeRoom.jsx
> feature: 이용자 내부방 목록 페이지에 좋아요 기능 추가

- src/Components/MainHeader.jsx
- src/Components/icons/IaddRoom.jsx
- src/Components/icons/Icalendar.jsx
- src/Components/icons/IfilledHeart.jsx
- src/Components/icons/Iheart.jsx
- src/Components/icons/Ipin.jsx
- src/Components/icons/Irevenue.jsx
- src/Components/icons/Isearch.jsx
- src/Components/icons/Iuser.jsx
- src/pages/Join/JoinInfo.jsx
- src/pages/MainPracticeRoom.jsx
- src/pages/Owner/AddPracticeRoom.jsx
- src/pages/Owner/OwnerPracticeRoom.jsx
- src/pages/User/User.jsx
> feature: svg 아이콘 변경

- package-lock.json
- package.json
- src/App.jsx
- src/Components/Calendar.jsx
- src/Components/MainHeader.jsx
- src/api/etc.js
- src/api/owner.js
- src/pages/Loading.jsx
- src/pages/Login.jsx
- src/pages/MainPracticeRoom.jsx
- src/pages/Owner/AddPracticeRoom.jsx
- src/pages/Owner/Owner.jsx
- src/pages/Owner/OwnerPracticeRoom.jsx
- src/pages/User/User.jsx
- src/pages/User/UserPayment.jsx
- src/router/BlockAdmin.jsx
- src/router/OnlyNotLogin.jsx
- src/router/OnlyOwner.jsx
- src/router/OnlyPending.jsx
- src/router/OnlyUser.jsx
> Feature add authorization

- src/App.jsx
- src/Components/AddPracticeRoom.jsx
- src/Components/DateSelector.jsx
- src/Components/PracticeRoomCard.jsx
- src/Components/icons/IaddRoom.jsx
- src/api/etc.js
- src/pages/Main.jsx
- src/pages/Owner/OwnerPracticeRoom.jsx
- src/pages/User/User.jsx
- src/pages/User/UserPayment.jsx
> Feature change firebase dir url

- src/Components/MainHeader.jsx
- src/Components/icons/Ibanner.jsx
- src/pages/Loading.jsx
- src/pages/Login.jsx
- src/pages/Main.jsx
- src/pages/MainPracticeRoom.jsx
> fix: 배너 로고 수정 & 카카오 결제 콜백 url 수정

- src/Components/DateSelector.jsx
- src/api/etc.js
- src/api/owner.js
- src/api/user.js
- src/pages/MainPracticeRoom.jsx
> feature: 이용자 연습실 내부방 조회 api 연결 & api 호출 함수들 주석 추가

- src/App.jsx
> test: join 페이지 테스트를 위해 임시로 권한 체크 주석처리

- src/App.jsx
- src/pages/KakaoLoginCallback.jsx
- src/pages/Loading.jsx
- src/pages/Login.jsx
> refactor: 로그인 콜백 페이지의 코드를 로딩 페이지로 이동

- src/Components/Button.jsx
- src/Components/icons/Ibanner.jsx
- src/pages/Join/JoinCategory.jsx
- src/pages/Join/JoinInfo.jsx
- src/pages/Loading.jsx
> fix: jwt decode 함수 호출

- src/App.jsx
- src/Components/PracticeRoomDetailCard.jsx
- src/api/etc.js
- src/api/user.js
- src/pages/Loading.jsx
- src/pages/MainPracticeRoom.jsx
- src/pages/User/UserPayment.jsx
> feature: 결재 중 오류 표시 및 이용자 내부방 목록 날짜 표시

- src/Components/MainHeader.jsx
- src/Components/PracticeRoomCard.jsx
- src/api/etc.js
- src/assets/category.js
- src/pages/Main.jsx
> feature: 연습실 목록 조회 api 수정

- package-lock.json
- src/Components/PracticeRoomCard.jsx
- src/pages/Main.jsx
- yarn.lock
> feature: 만실일 경우 못넘어가게 수정

- src/assets/category.js
- src/pages/Join/JoinCategory.jsx
- src/pages/Join/JoinInfo.jsx
- src/pages/Join/JoinSuccess.jsx
> :sparkles: Feat [#57] 유저 회원가입 api 연결

- package-lock.json
- package.json
- src/App.jsx
- src/Components/SelectTime.jsx
- src/pages/User/UserPayment.jsx
- yarn.lock
> feature: 시간 선택 UI 수정

- src/api/user.js
- src/pages/Join/JoinCategory.jsx
- src/pages/Join/JoinInfo.jsx
- src/pages/Join/JoinSuccess.jsx
- src/pages/MainPracticeRoom.jsx
- src/pages/Owner/AddPracticeRoom.jsx
- src/pages/Owner/OwnerPracticeRoom.jsx
- src/pages/User/UserPayment.jsx
- src/styles/react-ios-time-picker.css
> featur: 시간 선택 UI 일부 수정, 뒤로가기 url 수정, 카테고리 '전체' 추가

- src/Components/PracticeRoomCard.jsx
- src/pages/Join/JoinInfo.jsx
- src/pages/Main.jsx
- src/pages/MainPracticeRoom.jsx
> feature : 연습실 목록 표시 수정, 회원가입 api 수정

- src/App.jsx
- src/Components/ReservationCard.jsx
- src/pages/Login.jsx
- src/pages/Owner/Owner.jsx
- src/pages/User/User.jsx
> feature : 디자인 수정, 테스트 로그인 주석 처리, 마이페이지 오류 수정

- src/pages/Join/JoinCategory.jsx
- src/pages/Join/JoinInfo.jsx
- src/pages/MainPracticeRoom.jsx
- src/pages/Owner/AddPracticeRoom.jsx
- src/pages/Owner/OwnerPracticeRoom.jsx
- src/pages/User/UserReservation.jsx
> feature: 대여자 휴대폰 접근금지, 좋아요 목록 api 수정, 예약 취소 새로고침 추가

- src/pages/Join/JoinInfo.jsx
> feature: 휴대폰 대여자 회원가입 금지

- package-lock.json
- src/Components/Calendar.css
- src/pages/Owner/Owner.jsx
- yarn.lock
> feature: 오너 예약 디자인 수정

- src/pages/Join/JoinInfo.jsx
> feature: 회원가입 데이터 필수 입력 추가

- src/pages/Join/JoinInfo.jsx
> feature: 지역 input 주석처리
